apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: docker.pkg.github.com/ngkcl/space-apps-2019/app:{tag}
        name: app
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
      imagePullSecrets:
      - name: regcred

