name: Docker Image CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: >
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAYEAu3Yw6T/GIzj+SRABmw0wUdH84k5ZR9twgsJkujtM+LWXiic11ahi
          grDs9tBZNpspnIujuUdzMFlfG4dpr8HbF8uIFJqd/YougkuA9dt20XIRrwcSGh8oSJuwV5
          TOsZ8kufljshYeU/6ehHV01ANBsBkN8/J5kcUocBujkcljEJ+S/qWd56KJDIkEdcTuxM9P
          krLUyS7JjRTFToLSS5Ka1GR+pNylxxTQapSxLeZvDVg4bqNgvcSR8LP305rNq15p09bda9
          FV74upjNxq9yO+u+Zl0xhoA9e/foX1DPeVNgLA078JSbfJYQTyQuyU72UVW0NBkKIqkwKX
          OMzbnPiBJr3t5hxppos3C1dhNDf5n7kTRiuVIz0lXQXWxVYsS92jsMPpJ/OpA/ZYK44KK2
          SFgqhCPnimPg7yW3WRrIRzQpgxvqs/gapBvdHY8ZN65P4/qZQjCtKWA4ZHFslXx/s6lDn3
          h7BVEBBxFdTc95kB8bRiIy/1t/DFbJ67NCn6u7+bAAAFiLnlDum55Q7pAAAAB3NzaC1yc2
          EAAAGBALt2MOk/xiM4/kkQAZsNMFHR/OJOWUfbcILCZLo7TPi1l4onNdWoYoKw7PbQWTab
          KZyLo7lHczBZXxuHaa/B2xfLiBSanf2KLoJLgPXbdtFyEa8HEhofKEibsFeUzrGfJLn5Y7
          IWHlP+noR1dNQDQbAZDfPyeZHFKHAbo5HJYxCfkv6lneeiiQyJBHXE7sTPT5Ky1MkuyY0U
          xU6C0kuSmtRkfqTcpccU0GqUsS3mbw1YOG6jYL3EkfCz99OazateadPW3WvRVe+LqYzcav
          cjvrvmZdMYaAPXv36F9Qz3lTYCwNO/CUm3yWEE8kLslO9lFVtDQZCiKpMClzjM25z4gSa9
          7eYcaaaLNwtXYTQ3+Z+5E0YrlSM9JV0F1sVWLEvdo7DD6SfzqQP2WCuOCitkhYKoQj54pj
          4O8lt1kayEc0KYMb6rP4GqQb3R2PGTeuT+P6mUIwrSlgOGRxbJV8f7OpQ594ewVRAQcRXU
          3PeZAfG0YiMv9bfwxWyeuzQp+ru/mwAAAAMBAAEAAAGACvGhdVyFwrSnE7jdfyHL+lrZ+p
          Q8XhePf/K9Uqn3mmVvjV8wo2KLLboKe3Y6Xxe73CnCyyRCs0XkaYUERIB6u+7j6OAF7TFN
          +clSpAfF7gBMy/0Lr362KVb9en9zeaciy8Clc1YbOygYNP9ubJosEY3E5ML5Get6quDSMc
          aiA+xs9nTQvR8eBR9SpVVz4wV/Tb8m8P/MQHI/+o9km4jZhSDAy/sdqnuqly5LEbTsMsk9
          sifTlACPzI+VHkNhUmnWhi+uybW+erHNLOSwTNwF6d6IVZHTKPP/DUC7aBqlgTG7iccFPE
          M2I+39dj2iX6MafGiWsltF35NYjNHy0lyL14nb149K80eL6b/hswq/D3HyYX/JLhgVcPcR
          Oifdgsn8Vp44KCfvU4MtK/4Flbl0ABWAvvO7565PIJ/RFeLa4llA1yGZJc3e9cD46QtivI
          qmVUf1408mxLCR9oKj28VX9uKv+VaHo9I5akx2EPbZS7cKwdNk4s1KE/N3X51cNNBhAAAA
          wQDKZXUkuR4xFv1c4jQI5oAkq+z/X+TpzmYunDUSnQNVEtbi3LFXr3v1gCM0oh/zn1Trjy
          fXGxT3FLgn9M64hWBxZVfqZ3zTTA3T3jB1+jAIDjmBRyTbT3EuzJL2qB0HSKC/Plu5l2jS
          BvF39gCmRjtC/Lamh0TOiiYizD/Zdp+P4HlFBYO40tTYPuJyeEpSVz6ssb5JQzx6bg66yx
          K6TSwdndYKVnGIdgS/W0nI/l2nEbTOeOrkzf+WArMragkPkR0AAADBAORzAE8lPanIIG7q
          gD6UyyrWim2Aq2orDgOvi48ovKEz4fJTZ2tYV1TrO+pi8MvKbzZEPkupCjOCSEtm+FW63z
          S8pJcNKLk3YdpGf7+Xr0nOEzGqu6R+orzfP0ydl8UOPOYHMqmaILVsSwmpTPMixdthcL16
          +FCXU2MJ+3jzju4HAU7Tsx0jPy73PvVJln20HlZ9/k6RSHGO7ZvVi1dR9wrdM4plRiZqnU
          m5GOvnH7atvDTlGYBRaOUHpWUd9Xwc0wAAAMEA0hHEIMj8z1Awv5wxAd7sv7xWxe7weIsa
          lGlv/iOUvpyBPQzz8vOPApcku6A3QeH3rJ50JrtJIbpg2ShaoEYu/LsSWOLstxi84iAKE0
          7rk89Pm2JK+8hPb4okTbD5hJGib5FNjXckPtk6SSg2nNIpAG9PiHPrhkbbIKMkVuYVoTzN
          YimyK5XQIe2PR1ewwNtmyEtTfONa9oKdHxxSXh0JcV1gjv2k5x0/OIMNJogdNT/CG+pT1y
          AsIx71fEvdffUZAAAADmFsZXg0b0BhcmNodG9wAQIDBA==
          -----END OPENSSH PRIVATE KEY-----
    - name: Build the Docker image
      working-directory: ./back
      run: |
        docker build . --file Dockerfile --tag dokku/app:latest
        docker save dokku/app:latest | ssh footprints-space-apps.co "docker load | dokku tags:deploy app latest"
