name: Docker Image CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with: ${{ secrets.KURCHO_KEY }}
    - name: Build the Docker image
      working-directory: ./back
      run: |
        docker build . --file Dockerfile --tag dokku/app:latest
        docker save dokku/app:latest | ssh footprints-space-apps.co "docker load | dokku tags:deploy app latest"
