name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show kur4o > $GITHUB_WORKSPACE/.kubeconfig
    - name: Build the Docker image
      working-directory: ./back
      run: |
        docker build . --file Dockerfile --tag app:latest
    - name: Publish the Docker image
      working-directory: ./back
      run: |
        docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
        docker tag app:latest docker.pkg.github.com/ngkcl/space-apps-2019/app:$(echo $GITHUB_SHA | head -c7)
        docker push docker.pkg.github.com/ngkcl/space-apps-2019/app:$(echo $GITHUB_SHA | head -c7)
        sed "s/{tag}/$(echo $GITHUB_SHA | head -c7)/" ./kube/deploy.yaml > $GITHUB_WORKSPACE/deployment.yml
    - name: Deploy to DigitalOcean Kubernetes
      uses: docker://lachlanevenson/k8s-kubectl
      with:
        args: --kubeconfig=/github/workspace/.kubeconfig apply -n footprints -f /github/workspace/deployment.yml
    - name: Verify deployment
      uses: docker://lachlanevenson/k8s-kubectl
      with:
        args: --kubeconfig=/github/workspace/.kubeconfig rollout -n footprints status deployment.apps/app 
